version: '3'

services:

  app:
    container_name: frontend
    network_mode: bridge
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    container_name: backend
    network_mode: bridge
    env_file: ./backend/.env
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    build:
      context: './backend'
      dockerfile: './Dockerfile'
    restart: on-failure
    entrypoint: npm
    command: run start
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 8080:8080
    expose:
      - 8080

  mysql:
    image: mysql:5.7
    network_mode: bridge
    env_file: ./backend/.env
    ports:
      - 3306:3306
    expose:
      - 3306
